version: '3.7'

services:
  base: &base
    build: &build
      context: ./docker
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 80:80
    cap_add:
      - NET_ADMIN
    tty: true
    volumes:
      - ./begateway:/var/www/html/extension/begateway

  opencart:
    build:
      args:
        opencart_version: "opencart-4.0.2.3"
      <<: *build
    <<: *base

  db:
    image: mariadb:10.9
    volumes:
      - /var/lib/mysql
      - ./docker/etc/mysql/mysql.conf.d/sql_mode.cnf:/etc/mysql/mysql.conf.d/sql_mode.cnf
      - ./sql/install_begateway_extension.sql:/install_begateway_extension.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: opencart
